{
  "affected_release": [
    {
      "advisory": "RHSA-2015:1330",
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "package": "python-2.6.6-64.el6",
      "product_name": "Red Hat Enterprise Linux 6",
      "release_date": "2015-07-20T00:00:00"
    },
    {
      "advisory": "RHSA-2015:2101",
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "package": "python-2.7.5-34.el7",
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2015-11-19T00:00:00"
    },
    {
      "advisory": "RHSA-2015:1064",
      "cpe": "cpe:/a:redhat:rhel_software_collections:2::el6",
      "package": "python27-python-2.7.8-3.el6",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6",
      "release_date": "2015-06-04T00:00:00"
    },
    {
      "advisory": "RHSA-2015:1064",
      "cpe": "cpe:/a:redhat:rhel_software_collections:2::el7",
      "package": "python27-python-2.7.8-3.el7",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2015-06-04T00:00:00"
    }
  ],
  "bugzilla": {
    "description": "\nCVE-2013-1752 python: multiple unbound readline() DoS flaws in python stdlib\n    ",
    "id": "1046174",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1046174"
  },
  "cvss": {
    "cvss_base_score": "4.3",
    "cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "status": "verified"
  },
  "cwe": "CWE-400",
  "details": [
    "\n** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem.  When the candidate has been publicized, the details for this candidate will be provided.\n    ",
    "\nIt was discovered that multiple Python standard library modules implementing network protocols (such as httplib or smtplib) failed to restrict sizes of server responses. A malicious server could cause a client using one of the affected modules to consume an excessive amount of memory.\n    "
  ],
  "iava": "2014-B-0161",
  "name": "CVE-2013-1752",
  "package_state": [
    {
      "cpe": "cpe:/a:redhat:jboss_enterprise_application_platform:6",
      "fix_state": "Not affected",
      "package_name": "jython-eap6",
      "product_name": "Red Hat JBoss EAP 6"
    },
    {
      "cpe": "cpe:/a:redhat:jboss_enterprise_soa_platform:4.3",
      "fix_state": "Will not fix",
      "package_name": "jython",
      "product_name": "Red Hat JBoss Enterprise SOA Platform 4.3"
    },
    {
      "cpe": "cpe:/a:redhat:jboss_enterprise_soa_platform:5",
      "fix_state": "Will not fix",
      "package_name": "jython",
      "product_name": "Red Hat JBoss Enterprise SOA Platform 5"
    },
    {
      "cpe": "cpe:/a:redhat:network_satellite:5.4",
      "fix_state": "Will not fix",
      "package_name": "jython",
      "product_name": "Red Hat Satellite 5.4"
    },
    {
      "cpe": "cpe:/a:redhat:network_satellite:5.5",
      "fix_state": "Will not fix",
      "package_name": "jython",
      "product_name": "Red Hat Satellite 5.5"
    },
    {
      "cpe": "cpe:/a:redhat:openshift:2",
      "fix_state": "Will not fix",
      "package_name": "jython",
      "product_name": "Red Hat OpenShift Enterprise 2"
    },
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:2",
      "fix_state": "Not affected",
      "package_name": "rh-python34-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/a:redhat:rhel_software_collections:2",
      "fix_state": "Will not fix",
      "package_name": "python33-python",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Will not fix",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Will not fix",
      "package_name": "redhat-support-lib-python",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Will not fix",
      "package_name": "jython",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Will not fix",
      "package_name": "redhat-support-lib-python",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Will not fix",
      "package_name": "redhat-support-lib-python",
      "product_name": "Red Hat Enterprise Linux 7"
    }
  ],
  "public_date": "2012-09-25T00:00:00",
  "statement": "\nRed Hat JBoss SOA Platform 5 is now in Maintenance Support phase receiving only qualified Important and Critical impact security fixes; and Red Hat JBoss SOA Platform 4.3 is now in Extended Life Support phase receiving only Critical impact security fixes. This issue has been rated as having Moderate security impact and is not currently planned to be addressed in future updates. For additional information, refer to the Red Hat JBoss Middleware Product Life Cycle: https://access.redhat.com/support/policy/updates/jboss_notes/\n    ",
  "threat_severity": "Moderate",
  "upstream_fix": "python 3.2.6, python 3.3.4, python 3.4.0"
}