{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Virtualization 4",
      "fix_state": "Affected",
      "package_name": "nimbus-jose-jwt",
      "cpe": "cpe:/:redhat:enterprise_linux:::hypervisor"
    },
    {
      "product_name": "Red Hat Virtualization 4",
      "fix_state": "Will not fix",
      "package_name": "rhvm-dependencies",
      "cpe": "cpe:/:redhat:enterprise_linux:::hypervisor"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2019-10-15T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2019-17195 nimbus-jose-jwt: Uncaught exceptions while parsing a JWT",
    "id": "1764791",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1764791"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.5",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-248",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2019-17195",
  "document_distribution": "",
  "details": [
    "Connect2id Nimbus JOSE+JWT before v7.9 can throw various uncaught exceptions while parsing a JWT, which could result in an application crash (potential information disclosure) or a potential authentication bypass."
  ],
  "references": null
}