{
  "acknowledgement": "\nThis issue was discovered by Grzegorz Grasza (Red Hat).\n    ",
  "affected_release": {
    "advisory": "RHBA-2019:0944",
    "cpe": "cpe:/a:redhat:openstack:14::el7",
    "package": "python-novajoin-1.1.1-2.el7ost",
    "product_name": "Red Hat OpenStack Platform 14.0 (Rocky)",
    "release_date": "2019-04-30T00:00:00"
  },
  "bugzilla": {
    "description": "\nCVE-2019-10138 python-novajoin: novajoin API lacks access control\n    ",
    "id": "1670573",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1670573"
  },
  "cvss3": {
    "cvss3_base_score": "7.1",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
    "status": "verified"
  },
  "cwe": "CWE-284",
  "details": [
    "\n** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.\n    ",
    "\nA flaw was discovered in the python-novajoin plugin for Red Hat OpenStack Platform. The novajoin API lacked sufficient access control, allowing any keystone authenticated user to generate FreeIPA tokens.\n    "
  ],
  "name": "CVE-2019-10138",
  "package_state": {
    "cpe": "cpe:/a:redhat:openstack:13",
    "fix_state": "Affected",
    "package_name": "python-novajoin",
    "product_name": "Red Hat OpenStack Platform 13.0 (Queens)"
  },
  "public_date": "2019-01-17T00:00:00",
  "references": [
    "\nhttps://review.opendev.org/#/c/631240/\n    "
  ],
  "threat_severity": "Moderate",
  "upstream_fix": "python-novajoin 1.1.1"
}