{
  "affected_release": [
    {
      "product_name": "Red Hat OpenStack Platform 10",
      "release_date": "2017-04-12T00:00:00Z",
      "advisory": "RHSA-2017:0938",
      "package": "python-pysaml2-3.0.2-3.el7ost",
      "cpe": "cpe:/a:redhat:openstack:10::el7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)",
      "release_date": "2017-04-12T00:00:00Z",
      "advisory": "RHSA-2017:0936",
      "package": "python-pysaml2-3.0.2-3.el7ost",
      "cpe": "cpe:/a:redhat:openstack:8::el7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 9.0",
      "release_date": "2017-04-12T00:00:00Z",
      "advisory": "RHSA-2017:0937",
      "package": "python-pysaml2-3.0.2-3.el7ost",
      "cpe": "cpe:/a:redhat:openstack:9::el7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat OpenStack Platform 11.0 (Ocata)",
      "fix_state": "Not affected",
      "package_name": "python-pysaml2",
      "cpe": "cpe:/a:redhat:openstack:11"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7",
      "fix_state": "Will not fix",
      "package_name": "python-pysaml2",
      "cpe": "cpe:/a:redhat:openstack:7"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2016-10-31T00:00:00Z",
  "bugzilla": {
    "description": "\nCVE-2016-10149 python-pysaml2: Entity expansion issue\n    ",
    "id": "1415710",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1415710"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.3",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-776",
  "statement": "\nRed Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7: \nThis vulnerability has been rated as having a security impact of Moderate. After evaluation and in accordance with the criteria noted in the product support life cycle, there are no plans to address this issue in an upcoming release. Please contact Red Hat Support for further information.\n    ",
  "acknowledgement": "",
  "name": "CVE-2016-10149",
  "document_distribution": "",
  "details": [
    "\nXML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response.\n    ",
    "\nAn XML entity expansion vulnerability was found in python-pysaml2. A remote attacker could send a crafted request which would cause denial of service through resource exhaustion.\n    "
  ],
  "references": null
}