{
  "bugzilla": {
    "description": "\nCVE-2018-11499 libsass: Use-after-free vulnerability in sass_context.cpp:handle_error() can lead to denial of service or other unspecified impact\n    ",
    "id": "1583182",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1583182"
  },
  "cvss3": {
    "cvss3_base_score": "3.3",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
    "status": "draft"
  },
  "cwe": "CWE-416",
  "details": [
    "\nA use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.\n    "
  ],
  "name": "CVE-2018-11499",
  "package_state": {
    "cpe": "cpe:/o:redhat:enterprise_linux:8",
    "fix_state": "Affected",
    "package_name": "libsass",
    "product_name": "Red Hat Enterprise Linux 8"
  },
  "public_date": "2018-05-02T00:00:00",
  "threat_severity": "Low"
}