{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2019-08-06T00:00:00Z",
      "advisory": "RHSA-2019:2298",
      "package": "libarchive-3.1.2-12.el7",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Will not fix",
      "package_name": "libarchive",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "libarchive",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2017-09-16T00:00:00Z",
  "bugzilla": {
    "description": "\nCVE-2017-14503 libarchive: Out-of-bounds read in lha_read_data_none\n    ",
    "id": "1494449",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1494449"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "3.3",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2017-14503",
  "document_distribution": "",
  "details": [
    "\nlibarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.\n    "
  ],
  "references": null
}