{
  "affected_release": {
    "advisory": "RHSA-2019:2298",
    "cpe": "cpe:/o:redhat:enterprise_linux:7",
    "package": "libarchive-3.1.2-12.el7",
    "product_name": "Red Hat Enterprise Linux 7",
    "release_date": "2019-08-06T00:00:00"
  },
  "bugzilla": {
    "description": "\nCVE-2017-14503 libarchive: Out-of-bounds read in lha_read_data_none\n    ",
    "id": "1494449",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1494449"
  },
  "cvss3": {
    "cvss3_base_score": "3.3",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
    "status": "verified"
  },
  "cwe": "CWE-125",
  "details": [
    "\nlibarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.\n    "
  ],
  "name": "CVE-2017-14503",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "Will not fix",
      "package_name": "libarchive",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Will not fix",
      "package_name": "libarchive",
      "product_name": "Red Hat Enterprise Linux 8"
    }
  ],
  "public_date": "2017-09-16T00:00:00",
  "threat_severity": "Low",
  "upstream_fix": "libarchive 3.3.3"
}